// Phosphor icons mapped to Iconify icon names
export const icons = {
  'address-book': 'ph:address-book',
  'align-left': 'ph:align-left',
  'calendar-check': 'ph:calendar-check',
  'chart-pie': 'ph:chart-pie',
  'chart-line': 'ph:chart-line',
  'chats-circle': 'ph:chats-circle',
  'credit-card': 'ph:credit-card',
  'currency-eth': 'ph:currency-eth',
  'envelope-simple': 'ph:envelope-simple',
  'file-dashed': 'ph:file-dashed',
  'file-x': 'ph:file-x',
  'graduation-cap': 'ph:graduation-cap',
  'hard-drives': 'ph:hard-drives',
  'read-cv-logo': 'ph:read-cv-logo',
  'share-network': 'ph:share-network',
  'shield-warning': 'ph:shield-warning',
  'shopping-bag-open': 'ph:shopping-bag-open',
  'shopping-cart-simple': 'ph:shopping-cart-simple',
  'sign-out': 'ph:sign-out',
  'text-align-left': 'ph:text-align-left',
  'warning-diamond': 'ph:warning-diamond',
  cube: 'ph:cube',
  desktop: 'ph:desktop',
  file: 'ph:file',
  fire: 'ph:fire',
  funnel: 'ph:funnel',
  gateway: 'ph:cloud', // 网关应用图标
  gear: 'ph:gear',
  house: 'ph:house',
  kanban: 'ph:kanban',
  key: 'ph:key',
  laptop: 'ph:laptop',
  link: 'ph:link',
  lock: 'ph:lock',
  receipt: 'ph:receipt',
  sitemap: 'ph:tree-structure',
  truck: 'ph:truck',
  upload: 'ph:upload',
  users: 'ph:users',
} as Record<string, string>;
