export const navColorStyles = {
  dark: {
    blend_in: {
      '--SideNav-background': 'var(--chakra-colors-gray-50)',
      '--SideNav-color': 'var(--chakra-colors-white)',
      '--SideNav-border': '1px solid var(--chakra-colors-gray-600)',
      '--NavGroup-title-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-hover-background': 'var(--chakra-colors-gray-200)',
      '--NavItem-active-background': 'var(--chakra-colors-blue-500)',
      '--NavItem-active-color': 'var(--chakra-colors-blue-50)',
      '--NavItem-disabled-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-icon-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-icon-active-color': 'var(--chakra-colors-blue-50)',
      '--NavItem-icon-disabled-color': 'var(--chakra-colors-gray-600)',
      '--NavItem-expand-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-children-border': 'var(--chakra-colors-gray-600)',
      '--NavItem-children-indicator': 'var(--chakra-colors-gray-400)',
      '--Workspaces-background': 'var(--chakra-colors-gray-900)',
      '--Workspaces-border-color': 'var(--chakra-colors-gray-600)',
      '--Workspaces-title-color': 'var(--chakra-colors-gray-400)',
      '--Workspaces-name-color': 'var(--chakra-colors-gray-300)',
      '--Workspaces-expand-color': 'var(--chakra-colors-gray-400)',
    },
    discrete: {
      '--SideNav-background': 'var(--chakra-colors-gray-900)',
      '--SideNav-color': 'var(--chakra-colors-white)',
      '--SideNav-border': '1px solid var(--chakra-colors-gray-700)',
      '--NavGroup-title-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-hover-background': 'var(--chakra-colors-gray-200)',
      '--NavItem-active-background': 'var(--chakra-colors-blue-500)',
      '--NavItem-active-color': 'var(--chakra-colors-blue-50)',
      '--NavItem-disabled-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-icon-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-icon-active-color': 'var(--chakra-colors-blue-50)',
      '--NavItem-icon-disabled-color': 'var(--chakra-colors-gray-600)',
      '--NavItem-expand-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-children-border': 'var(--chakra-colors-gray-700)',
      '--NavItem-children-indicator': 'var(--chakra-colors-gray-400)',
      '--Workspaces-background': 'var(--chakra-colors-gray-900)',
      '--Workspaces-border-color': 'var(--chakra-colors-gray-700)',
      '--Workspaces-title-color': 'var(--chakra-colors-gray-400)',
      '--Workspaces-name-color': 'var(--chakra-colors-gray-300)',
      '--Workspaces-expand-color': 'var(--chakra-colors-gray-400)',
    },
    evident: {
      '--SideNav-background': 'var(--chakra-colors-gray-800)',
      '--SideNav-color': 'var(--chakra-colors-white)',
      '--SideNav-border': 'none',
      '--NavGroup-title-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-hover-background': 'rgba(255, 255, 255, 0.04)',
      '--NavItem-active-background': 'var(--chakra-colors-blue-500)',
      '--NavItem-active-color': 'var(--chakra-colors-blue-50)',
      '--NavItem-disabled-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-icon-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-icon-active-color': 'var(--chakra-colors-blue-50)',
      '--NavItem-icon-disabled-color': 'var(--chakra-colors-gray-600)',
      '--NavItem-expand-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-children-border': 'var(--chakra-colors-gray-700)',
      '--NavItem-children-indicator': 'var(--chakra-colors-gray-400)',
      '--Workspaces-background': 'var(--chakra-colors-gray-900)',
      '--Workspaces-border-color': 'var(--chakra-colors-gray-700)',
      '--Workspaces-title-color': 'var(--chakra-colors-gray-400)',
      '--Workspaces-name-color': 'var(--chakra-colors-gray-300)',
      '--Workspaces-expand-color': 'var(--chakra-colors-gray-400)',
    },
  },
  light: {
    blend_in: {
      '--SideNav-background': 'var(--chakra-colors-gray-50)',
      '--SideNav-color': 'var(--chakra-colors-gray-900)',
      '--SideNav-border': '1px solid var(--chakra-colors-gray-200)',
      '--NavGroup-title-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-hover-background': 'var(--chakra-colors-gray-100)',
      '--NavItem-active-background': 'var(--chakra-colors-blue-500)',
      '--NavItem-active-color': 'var(--chakra-colors-white)',
      '--NavItem-disabled-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-icon-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-icon-active-color': 'var(--chakra-colors-white)',
      '--NavItem-icon-disabled-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-expand-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-children-border': 'var(--chakra-colors-gray-100)',
      '--NavItem-children-indicator': 'var(--chakra-colors-gray-300)',
      '--Workspaces-background': 'var(--chakra-colors-gray-100)',
      '--Workspaces-border-color': 'var(--chakra-colors-gray-200)',
      '--Workspaces-title-color': 'var(--chakra-colors-gray-400)',
      '--Workspaces-name-color': 'var(--chakra-colors-gray-900)',
      '--Workspaces-expand-color': 'var(--chakra-colors-gray-400)',
    },
    discrete: {
      '--SideNav-background': 'var(--chakra-colors-gray-50)',
      '--SideNav-color': 'var(--chakra-colors-gray-900)',
      '--SideNav-border': '1px solid var(--chakra-colors-gray-200)',
      '--NavGroup-title-color': 'var(--chakra-colors-gray-600)',
      '--NavItem-color': 'var(--chakra-colors-gray-600)',
      '--NavItem-hover-background': 'var(--chakra-colors-gray-100)',
      '--NavItem-active-background': 'var(--chakra-colors-blue-500)',
      '--NavItem-active-color': 'var(--chakra-colors-white)',
      '--NavItem-disabled-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-icon-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-icon-active-color': 'var(--chakra-colors-white)',
      '--NavItem-icon-disabled-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-expand-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-children-border': 'var(--chakra-colors-gray-200)',
      '--NavItem-children-indicator': 'var(--chakra-colors-gray-500)',
      '--Workspaces-background': 'var(--chakra-colors-gray-100)',
      '--Workspaces-border-color': 'var(--chakra-colors-gray-200)',
      '--Workspaces-title-color': 'var(--chakra-colors-gray-400)',
      '--Workspaces-name-color': 'var(--chakra-colors-gray-900)',
      '--Workspaces-expand-color': 'var(--chakra-colors-gray-400)',
    },
    evident: {
      '--SideNav-background': 'var(--chakra-colors-gray-900)',
      '--SideNav-color': 'var(--chakra-colors-white)',
      '--SideNav-border': 'none',
      '--NavGroup-title-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-color': 'var(--chakra-colors-gray-300)',
      '--NavItem-hover-background': 'rgba(255, 255, 255, 0.04)',
      '--NavItem-active-background': 'var(--chakra-colors-blue-500)',
      '--NavItem-active-color': 'var(--chakra-colors-white)',
      '--NavItem-disabled-color': 'var(--chakra-colors-gray-500)',
      '--NavItem-icon-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-icon-active-color': 'var(--chakra-colors-white)',
      '--NavItem-icon-disabled-color': 'var(--chakra-colors-gray-600)',
      '--NavItem-expand-color': 'var(--chakra-colors-gray-400)',
      '--NavItem-children-border': 'var(--chakra-colors-gray-700)',
      '--NavItem-children-indicator': 'var(--chakra-colors-gray-400)',
      '--Workspaces-background': 'var(--chakra-colors-gray-900)',
      '--Workspaces-border-color': 'var(--chakra-colors-gray-700)',
      '--Workspaces-title-color': 'var(--chakra-colors-gray-400)',
      '--Workspaces-name-color': 'var(--chakra-colors-gray-300)',
      '--Workspaces-expand-color': 'var(--chakra-colors-gray-400)',
    },
  },
};
