export const navColorStyles = {
  dark: {
    blend_in: {
      '--MainNav-background': 'gray.800',
      '--MainNav-color': 'white',
      '--MainNav-border': '1px solid',
      '--MainNav-divider': 'gray.700',
      '--NavItem-color': 'gray.300',
      '--NavItem-hover-background': 'gray.900',
      '--NavItem-active-background': 'blue.500',
      '--NavItem-active-color': 'white',
      '--NavItem-disabled-color': 'gray.600',
      '--NavItem-icon-color': 'gray.400',
      '--NavItem-icon-active-color': 'white',
      '--NavItem-icon-disabled-color': 'gray.500',
      '--NavItem-expand-color': 'gray.400',
      '--Workspaces-background': 'gray.950',
      '--Workspaces-border-color': 'gray.700',
      '--Workspaces-title-color': 'gray.400',
      '--Workspaces-name-color': 'gray.300',
      '--Workspaces-expand-color': 'gray.400',
    },
    discrete: {
      '--MainNav-background': 'gray.900',
      '--MainNav-color': 'white',
      '--MainNav-border': '1px solid',
      '--MainNav-divider': 'gray.700',
      '--NavItem-color': 'gray.300',
      '--NavItem-hover-background': 'gray.100',
      '--NavItem-active-background': 'blue.500',
      '--NavItem-active-color': 'white',
      '--NavItem-disabled-color': 'gray.500',
      '--NavItem-icon-color': 'gray.400',
      '--NavItem-icon-active-color': 'white',
      '--NavItem-icon-disabled-color': 'gray.600',
      '--NavItem-expand-color': 'gray.400',
      '--Workspaces-background': 'gray.950',
      '--Workspaces-border-color': 'gray.700',
      '--Workspaces-title-color': 'gray.400',
      '--Workspaces-name-color': 'gray.300',
      '--Workspaces-expand-color': 'gray.400',
    },
    evident: {
      '--MainNav-background': 'gray.800',
      '--MainNav-color': 'white',
      '--MainNav-border': 'none',
      '--MainNav-divider': 'gray.700',
      '--NavItem-color': 'gray.300',
      '--NavItem-hover-background': 'rgba(255, 255, 255, 0.04)',
      '--NavItem-active-background': 'blue.500',
      '--NavItem-active-color': 'white',
      '--NavItem-disabled-color': 'gray.500',
      '--NavItem-icon-color': 'gray.400',
      '--NavItem-icon-active-color': 'white',
      '--NavItem-icon-disabled-color': 'gray.600',
      '--NavItem-expand-color': 'gray.400',
      '--Workspaces-background': 'gray.950',
      '--Workspaces-border-color': 'gray.700',
      '--Workspaces-title-color': 'gray.400',
      '--Workspaces-name-color': 'gray.300',
      '--Workspaces-expand-color': 'gray.400',
    },
  },
  light: {
    blend_in: {
      '--MainNav-background': 'gray.50',
      '--MainNav-color': 'black',
      '--MainNav-border': '1px solid',
      '--MainNav-divider': 'gray.200',
      '--NavItem-color': 'gray.600',
      '--NavItem-hover-background': 'gray.100',
      '--NavItem-active-background': 'blue.500',
      '--NavItem-active-color': 'white',
      '--NavItem-disabled-color': 'gray.500',
      '--NavItem-icon-color': 'gray.500',
      '--NavItem-icon-active-color': 'white',
      '--NavItem-icon-disabled-color': 'gray.500',
      '--NavItem-expand-color': 'gray.500',
      '--Workspaces-background': 'gray.100',
      '--Workspaces-border-color': 'gray.200',
      '--Workspaces-title-color': 'gray.400',
      '--Workspaces-name-color': 'gray.900',
      '--Workspaces-expand-color': 'gray.400',
    },
    discrete: {
      '--MainNav-background': 'gray.50',
      '--MainNav-color': 'black',
      '--MainNav-border': '1px solid',
      '--MainNav-divider': 'gray.200',
      '--NavGroup-title-color': 'gray.600',
      '--NavItem-color': 'gray.600',
      '--NavItem-hover-background': 'gray.100',
      '--NavItem-active-background': 'blue.500',
      '--NavItem-active-color': 'white',
      '--NavItem-disabled-color': 'gray.500',
      '--NavItem-icon-color': 'gray.500',
      '--NavItem-icon-active-color': 'white',
      '--NavItem-icon-disabled-color': 'gray.500',
      '--NavItem-expand-color': 'gray.500',
      '--Workspaces-background': 'gray.100',
      '--Workspaces-border-color': 'gray.200',
      '--Workspaces-title-color': 'gray.400',
      '--Workspaces-name-color': 'gray.900',
      '--Workspaces-expand-color': 'gray.400',
    },
    evident: {
      '--MainNav-background': 'gray.900',
      '--MainNav-color': 'white',
      '--MainNav-border': 'none',
      '--MainNav-divider': 'gray.700',
      '--NavItem-color': 'gray.300',
      '--NavItem-hover-background': 'rgba(255, 255, 255, 0.04)',
      '--NavItem-active-background': 'blue.500',
      '--NavItem-active-color': 'white',
      '--NavItem-disabled-color': 'gray.500',
      '--NavItem-icon-color': 'gray.400',
      '--NavItem-icon-active-color': 'white',
      '--NavItem-icon-disabled-color': 'gray.600',
      '--NavItem-expand-color': 'gray.400',
      '--Workspaces-background': 'gray.950',
      '--Workspaces-border-color': 'gray.700',
      '--Workspaces-title-color': 'gray.400',
      '--Workspaces-name-color': 'gray.300',
      '--Workspaces-expand-color': 'gray.400',
    },
  },
};
